server:
  address: 0.0.0.0
  port: 8104
  servlet:
    context-path: /api/judge
    # cookie 30 天过期（用户登录信息保存在session中）
    session:
      cookie:
        max-age: 2592000
        #解决 cookie 跨路径问题
        path: /api

spring:
  application:
    name: oj-backend-judge-service
  # 注册到 nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    host: 127.0.0.1 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: guest # 用户名
    password: guest # 密码
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期（用户登录信息保存在session中）
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj
    username: root
    password: 1234
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    #数据库1
    database: 1
    host: 192.168.200.138
    port: 6379
    timeout: 5000
    password: 1234
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

knife4j:
  enable: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

#代码沙箱配置
codeSandBox:
  type: remote
  # 代码沙箱地址
  url: http://127.0.0.1:8105/api/executeCode
#  url: http://192.168.200.138:8105/api/executeCode